---
x-defaults: &defaults
  env_file:
    - ./config/tuoni.env
  restart: unless-stopped
  extra_hosts:
    - host.docker.internal:host-gateway
    - local-c2:host-gateway
    - ${DOCKER_HOST_FQDN}:host-gateway
  logging:
    driver: json-file
    options:
      max-size: 250m
      max-file: "1"

services:
  tuoni-server:
    <<: *defaults
    profiles: ["app", "server"]
    container_name: tuoni-server
    hostname: tuoni-server
    image: ghcr.io/shell-dot/tuoni/server:${VERSION}
    volumes:
      - ./data/:/app/data/
      - ./logs/server/:/app/logs/
      - ./payload-templates/:/app/custom-payload-templates/:ro
      - ./config/tuoni.yml:/app/tuoni-production.yml:ro
      - ./ssl/server/server-selfsigned.keystore:/app/ssl/selfsigned.keystore:ro
      - ./ssl/server/server-private.pem:/app/prod-private.pem:ro
      - ./ssl/server/server-public.pem:/app/prod-public.pem:ro
      - ./plugins/server/:/app/plugins/:ro
    network_mode: host

  tuoni-client:
    <<: *defaults
    profiles: ["app", "client"]
    container_name: tuoni-client
    hostname: tuoni-client
    image: ghcr.io/shell-dot/tuoni/client:${VERSION}
    user: 1000:100
    environment:
      - TUONI_CLIENT_PORT
      - NUXT_LOGGER_ENABLED=${TUONI_CLIENT_LOGGER_ENABLED}
      - NUXT_LOGGER_CONSOLE=${TUONI_CLIENT_LOGGER_CONSOLE}
      - NUXT_LOGGER_LEVEL=${TUONI_CLIENT_LOGGER_LEVEL}
      - NUXT_LOGGER_HEADERS=${TUONI_CLIENT_LOGGER_HEADERS}
      - NUXT_LOGGER_SH=${TUONI_CLIENT_LOGGER_SH}
    volumes:
      - ./logs/client/:/srv/logs/client/:rw
      - ./plugins/client:/srv/user-defined-plugins/:ro

  tuoni-client-nginx:
    <<: *defaults
    profiles: ["app", "client", "client-nginx"]
    container_name: tuoni-client-nginx
    hostname: tuoni-client-nginx
    image: nginx:latest
    ports:
      - "${TUONI_CLIENT_PORT}:${TUONI_CLIENT_PORT}"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./nginx/502_504.html:/var/www/errors/502_504.html:ro
      - ./ssl/client/client.crt:/etc/nginx/certs/tuoni.crt:ro
      - ./ssl/client/client-private.pem:/etc/nginx/certs/tuoni.key:ro
      ### uncomment to direct logs to file
      ### - ./logs/nginx/:/var/log/nginx/:rw