#!/bin/bash

. ./scripts/_init.sh
. ./scripts/check-os.sh
. ./scripts/check-packages.sh
. ./scripts/check-docker.sh
. ./scripts/check-configuration.sh
### include env variables
. ./config/tuoni.env

### full app
. ./scripts/tuoni-command.sh $1
