---
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: selfsigned
    key-store: ssl/selfsigned.keystore
    key-store-type: jks
    key-store-password: selfsigned
    key-password: selfsigned

tuoni:
  data-dir: ./data

  auth:
    credentials:
      username: _credentials_placeholder_username_
      password: _credentials_placeholder_password_
    jwt:
      expiry-seconds: 86400
      private-key: file:./prod-private.pem
      public-key: file:./prod-public.pem
  plugins:
    "[shelldot.payload.default]":
      configuration:
        custom-payload-template-dir: file:./custom-payload-templates/

  # EXPERIMENTAL
  scripting:
    permissions:
      # Options are
      # - "sandbox" - read access to Tuoni scripts, files and GraalPy. Read-write access to /tuoni_vfs/tmp directory.
      # - "read-only" - read access to Tuoni scripts, files, and the real file system. Read-write access to /tuoni_vfs/tmp directory.
      # - "read-write" - read-write access to Tuoni scripts, the real file system, and to /tuoni_vfs/tmp directory. Read-only for Tuoni files.
      fs-access: "sandbox"
      allow-net-access: false
      allow-env-access: false

logging:
  file:
    name: ./logs/tuoni-server.log
  threshold:
    console: INFO
    file: DEBUG
  level:
    com.shelldot.tuoni: debug
    root: info
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB

client:
  port: 12702
  logger:
    to_file: false
    to_console: false
    level: info
    sh: false
    headers:
      - user-agent
